version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./resources/database:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_PASSWORD:root